python3 main.py 0 '../data/noImprInLoop_default_OD' &
python3 main.py 1 '../data/noImprInLoop_default_OD' &
python3 main.py 2 '../data/noImprInLoop_default_OD' &
python3 main.py 3 '../data/noImprInLoop_default_OD' &
python3 main.py 4 '../data/noImprInLoop_default_OD' &
python3 main.py 5 '../data/noImprInLoop_default_OD' &
python3 main.py 6 '../data/noImprInLoop_default_OD' &
python3 main.py 7 '../data/noImprInLoop_default_OD' &
python3 main.py 8 '../data/noImprInLoop_default_OD' &
python3 main.py 9 '../data/noImprInLoop_default_OD' &
python3 main.py 10 '../data/noImprInLoop_default_OD' &
python3 main.py 11 '../data/noImprInLoop_default_OD' &
python3 main.py 12 '../data/noImprInLoop_default_OD' &
python3 main.py 13 '../data/noImprInLoop_default_OD' &
python3 main.py 14 '../data/noImprInLoop_default_OD' &
python3 main.py 15 '../data/noImprInLoop_default_OD' &
python3 main.py 16 '../data/noImprInLoop_default_OD' &
python3 main.py 17 '../data/noImprInLoop_default_OD' &
python3 main.py 18 '../data/noImprInLoop_default_OD' &
python3 main.py 19 '../data/noImprInLoop_default_OD' &
python3 main.py 20 '../data/noImprInLoop_default_OD' &
python3 main.py 21 '../data/noImprInLoop_default_OD' &
